name: Daily Meeting History Sync

on:
  schedule:
    # 毎日日本時間23:30 (UTC 14:30)に実行
    - cron: '30 14 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  sync-meeting-data:
    runs-on: ubuntu-latest
    
    environment: production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Set timezone to JST
      run: |
        sudo timedatectl set-timezone Asia/Tokyo
        date
        
    - name: Create Google Service Account JSON
      run: |
        echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > google-service-account.json
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        
    - name: Run daily sync
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        GOOGLE_SERVICE_ACCOUNT_PATH: ./google-service-account.json
        GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
        TZ: Asia/Tokyo
      run: |
        echo "🚀 Starting daily meeting history sync at $(date '+%Y-%m-%d %H:%M:%S %Z')"
        echo "📅 Syncing data for $(date '+%Y-%m-%d')"
        npm run sync-history daily
        echo "✅ Daily sync completed at $(date '+%Y-%m-%d %H:%M:%S %Z')"
        
    - name: Clean up secrets
      if: always()
      run: rm -f google-service-account.json
      
    - name: Send notification on failure
      if: failure()
      run: |
        echo "❌ Daily sync failed at $(date '+%Y-%m-%d %H:%M:%S %Z')"
        echo "Please check the workflow logs for details."
        echo "Workflow URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"