name: Manual Meeting History Sync

on:
  workflow_dispatch:
    inputs:
      sync_type:
        description: 'Sync type (daily or bulk)'
        required: true
        default: 'daily'
        type: choice
        options:
        - daily
        - bulk
      start_date:
        description: 'Start date (YYYY-MM-DD) - for bulk sync only'
        required: false
        type: string
        default: ''
      end_date:
        description: 'End date (YYYY-MM-DD) - for bulk sync only'
        required: false
        type: string
        default: ''

jobs:
  manual-sync:
    runs-on: ubuntu-latest
    
    environment: production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Set timezone to JST
      run: |
        sudo timedatectl set-timezone Asia/Tokyo
        date
        
    - name: Create Google Service Account JSON
      run: |
        echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > google-service-account.json
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        
    - name: Validate inputs for bulk sync
      if: github.event.inputs.sync_type == 'bulk'
      run: |
        if [ -z "${{ github.event.inputs.start_date }}" ] || [ -z "${{ github.event.inputs.end_date }}" ]; then
          echo "❌ Error: Both start_date and end_date are required for bulk sync"
          exit 1
        fi
        echo "📅 Bulk sync: ${{ github.event.inputs.start_date }} to ${{ github.event.inputs.end_date }}"
        
    - name: Run daily sync
      if: github.event.inputs.sync_type == 'daily'
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        GOOGLE_SERVICE_ACCOUNT_PATH: ./google-service-account.json
        GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
        TZ: Asia/Tokyo
      run: |
        echo "🚀 Starting manual daily sync at $(date '+%Y-%m-%d %H:%M:%S %Z')"
        npm run sync-history daily
        echo "✅ Manual daily sync completed at $(date '+%Y-%m-%d %H:%M:%S %Z')"
        
    - name: Run bulk sync
      if: github.event.inputs.sync_type == 'bulk'
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        GOOGLE_SERVICE_ACCOUNT_PATH: ./google-service-account.json
        GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
        TZ: Asia/Tokyo
      run: |
        echo "🚀 Starting manual bulk sync at $(date '+%Y-%m-%d %H:%M:%S %Z')"
        echo "📅 Period: ${{ github.event.inputs.start_date }} to ${{ github.event.inputs.end_date }}"
        npm run sync-history bulk ${{ github.event.inputs.start_date }} ${{ github.event.inputs.end_date }}
        echo "✅ Manual bulk sync completed at $(date '+%Y-%m-%d %H:%M:%S %Z')"
        
    - name: Clean up secrets
      if: always()
      run: rm -f google-service-account.json
      
    - name: Send notification on failure
      if: failure()
      run: |
        echo "❌ Manual sync failed at $(date '+%Y-%m-%d %H:%M:%S %Z')"
        echo "Sync type: ${{ github.event.inputs.sync_type }}"
        if [ "${{ github.event.inputs.sync_type }}" == "bulk" ]; then
          echo "Period: ${{ github.event.inputs.start_date }} to ${{ github.event.inputs.end_date }}"
        fi
        echo "Workflow URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"